### ISSUE TITLE
`demos/print_help` Doesn't Work After the Connectionless API Changes

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#211]
The file is:
```
help;
connect container-jfr:9091;
help;
```
But we don't have the `connect` command anymore, so running it with `sh run.sh "$(more demos/print_help)"` doesn't work.

We could fix it by having the file just be:
```
help;
```

But at that point maybe it would be better to just tell the reader to run `help` themselves? Since now there isn't two sets of commands (connected/unconnected), so all they need to do is type `help` into the interactive execution.

Or was the point of `print_help` to demonstrate the batch mode execution?

**Comment by andrewazores** [comment]
The whole idea of the demo is pretty outdated anyway. That dates back to long before there was a WebSocket API and serialized execution - at the time, there was only the interactive mode, either directly in "shell" mode or via TCP socket. I think just removing the demos and any reference to them is probably the best bet. The WebSocket + HTTP APIs are what's important, and the demos don't make sense in that context. I'm in favour of removing the interactive mode executor soon, and the TCP socket executor should be removed even sooner since it doesn't have any notion of connection security even.
