### ISSUE TITLE
HTTP API should support recording options

### ISSUE THREAD

**Issue by Alexjsenn** [rh-jmc-team/container-jfr#250]
The following proposed changes would enable the web client to show and modify recording options such as toDisk, maxAge and maxSize.

#### New Recordings
Create a new recording on a target JVM
Method: `POST /api/v1/targets/targetId/recordings`
New (optional) request body attributes:
* **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*
* **setDefault** *bool*

#### Default recording options
Retrieve or set default recording options that apply to recordings created on any JVM target

Method: `GET /api/v1/recordingOptions`
Response attributes:
 * **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*

Method: `POST /api/v1/recordingOptions`
Request body attributes:
 * **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*

**Comment by andrewazores** [comment]
Sounds reasonable.

What do you envision `setDefault bool` being used for on the creation `POST`? Is this to add a side-effect of writing the option values provided with the request to the ContainerJFR global state?

For the `POST`s, I assume the attributes would be form-encoded? And the `GET` response would simply be JSON with each of the attributes as keys of a single top-level "dictionary"-like object?

**Comment by Alexjsenn** [comment]
Regarding the `setDefault` bool, It could allow the user to set the options to the global state (with a checkbox or something in the UI). I guess it depends if we want there to be a different interface to change the defaults, or if it is just an option when creating a recording.
 
For the `POST`s the attributes should be form encoded given that is the current format for the existing recordings endpoint, and for the `GET` response JSON would be the most straight forward, but I am not sure if there are any standards or preferences.

**Comment by andrewazores** [comment]
> Regarding the setDefault bool, It could allow the user to set the options to the global state (with a checkbox or something in the UI). I guess it depends if we want there to be a different interface to change the defaults, or if it is just an option when creating a recording.

I think we should have a UI for setting the defaults, although that can be done as a separate UI enhancement with a separate API addition later perhaps, just in the interest of keeping things small and easily reviewable.

I would prefer not to have the `setDefault` at all here. The effects of the POST should only be that a recording is created (or not, if the request is invalid or otherwise fails), and not have any other side-effect like setting global state dependent on the form submission.

The UI can gain a "Set these options as default for the future" checkbox later, but if it does, this should be implemented as the UI performing a separate call to the hypothetical endpoint that is used for updating the defaults, not by including a parameter on the recording creation.

> For the POSTs the attributes should be form encoded given that is the current format for the existing recordings endpoint, and for the GET response JSON would be the most straight forward, but I am not sure if there are any standards or preferences.

That's all fine. I just wanted to clarify since it wasn't explicitly mentioned yet.

**Comment by Alexjsenn** [comment]
Ok, that makes a lot of sense, I remember reading about good principles for APIs and yes, I won't include `setDefault`. Given that the recording options `POST' doesn't have a use in the front end yet, should I keep it here or not?

**Comment by andrewazores** [comment]
Yes, I think so. It can be included in this issue and implemented in advance of the web-client or operator having a use for it.

Also,

> Method: POST /api/v1/recordingOptions

`POST` is probably appropriate here, but I wonder if `PUT` might be more appropriate and informative? `PUT` would imply that the server state is set/replaced but there are no other side-effects like creation of any new resource. `POST` would normally come with the implication that a new resource exists afterward, which would not be the case here.

A `PATCH` endpoint could also be implemented allowing clients to update the state without providing values for all of the attributes, but that's a lower priority IMO since it's just a very minor optimization compared to `PUT`.

**Comment by Alexjsenn** [comment]
Yes, `PUT` makes more sense! should I edit the above proposal with these changes?

**Comment by andrewazores** [comment]
Sure, or post a revision here in the comments. So long as we have some up-to-date proposal that we can refer back to when the implementation is in progress.

**Comment by Alexjsenn** [comment]
Revised Proposal

### Changes
#### New Recordings
Create a new recording on a target JVM
Method: `POST /api/v1/targets/targetId/recordings`
Request body format: Form-encoded
New (optional) request body attributes:
* **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*

### Additions
#### Default recording options
Retrieve or set default recording options that apply to recordings created on any JVM target

Method: `GET /api/v1/recordingOptions`
Response body format: JSON
Response attributes:
 * **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*

Method: `PUT /api/v1/recordingOptions`
Request body format: Form-encoded
Request body attributes:
 * **toDisk** *bool*
* **maxAge** *integer (seconds)*
* **maxSize** *integer (bytes)*

**Comment by andrewazores** [comment]
Looks good to me.
