### ISSUE TITLE
Communication channels must be secured

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#9]
HTTPS and WSS should be used, not plain HTTP and WS.

**Comment by tabjy** [comment]
I'm wondering what approach you'd like. As far as I know, when openshift route exposes an http or a ws service, one already has the optional to secure connections, and the encryption and cert management would be handled by openshift. (ie. SSL termination)

Alternatively, container-jfr itself can look for two env vars pointing to `.key` and `.cert` files (or a single `.pfx` or `.pem` file, I don't yet know what NanoHTTPD and Jetty accept), and secure connections end-to-end. I'm not sure how openshift is gonna route requests by hostname since the request, which contains the `Host` header, is now encrypted and not understandable to openshift.

But yes, the latter is more beneficial if deployed in a non-orchestrated container environment (ie. plain docker), or other Kubernetes distributions which don't provide SSL termination.

**Comment by andrewazores** [comment]
> Alternatively, container-jfr itself can look for two env vars pointing to `.key` and `.cert` files (or a single `.pfx` or `.pem` file, I don't yet know what NanoHTTPD and Jetty accept), and secure connections end-to-end. I'm not sure how openshift is gonna route requests by hostname since the request, which contains the `Host` header, is now encrypted and not understandable to openshift.

Right, whatever solution is implemented will need to be something that can be enabled or disabled for each deployment as needed. If whatever configuration is required (environment variables for example) are not set/do not exist, then the SSL parts should indeed be disabled and everything falls back to standard, unsecured traffic. As you point out, this is useful for other deployment scenarios which don't necessarily have some kind of proxy in front of the service like Kubernetes/OpenShift does. There's also the simple use case of running as a local JVM process, as a sort of headless JMC instance, which probably doesn't have much use for encrypted connections since connections are probably only coming from the same local machine.

I don't think it's worth trying to support SSL for both NanoHTTPD and Jetty, so it seems to make sense to clean up and switch over to only one webserver to handle HTTP(S) and WS(S) traffic first. Whether that's Jetty or some other webserver is open for discussion. Once that work is completed then enabling SSL for the webserver should be much cleaner.

**Comment by tabjy** [comment]
Sounds good. I'll get back to this once cleaned up.
